# **NUMPY**

Bibilioteca do python que permite a criação de arrays, que são estruturas mais complexas e multidimensionais, como também possui funções matemáticas pré definidas.

Vantagens:

*   É mais eficiente que listas convencionais
*   Utiliza menos memória
*   Permite broadcasting
*   Possui integração com outras bibliotecas importantes para análise de dados, como pandas e TensorFlow



## *Instalação e importação*

In [2]:
#Comando para instalar a biblioteca
!pip install numpy

In [3]:
#Importando a biblioteca com alias
import numpy as np

In [10]:
#Diferença de tempo na prática entre ambas estruturas
#Primeiro: tempo em listas convencionais

from time import time
inicio = time()
lista1 = list(range(10**8))
soma1 = 0
for i in lista1:
  soma1 += i
fim = time()

print(fim - inicio)

17.829976797103882


In [9]:
#Agora com arrays
inicio2 = time()
array1 = np.array(lista1, dtype = float)
soma2 = array1.sum()
fim2 = time()

print(fim2 - inicio2)

7.555789232254028


## *Introdução aos Arrays*

In [12]:
#Criação de um array a partir de uma lista, utilizando o método .array()
array1 = np.array([0,1,2,3,4,5])
print(array1)
print(type(array1)) #verificando o tipo da estrutura

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [18]:
#Criando uma matriz - um array de 2 dimensões
array2 = np.array([[1,2,3,4],[4,3,2,1]])
print(array2)
print(type(array2))

[[1 2 3 4]
 [4 3 2 1]]
<class 'numpy.ndarray'>


In [20]:
#Array de 3 dimensões
array3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [22]:
#Criar array de N dimensões
#Utiliza o ndmin
arrayn = np.array([1,2,3,4,5], ndmin = 5)
print(arrayn)

[[[[[1 2 3 4 5]]]]]


In [24]:
#Para se verificar a quantidade de dimensões que um array
#existente tem, utiliza-se o .ndim
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)
print(arrayn.ndim)

1
2
3
5


In [27]:
#Criação de array utilizando o NP Arange, método similar a criação de listas usando o range
array4 = np.arange(21) #array com os inteiros de 0 a 20
print(array4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [28]:
#Utilizando o NP Arange com passo
passo = 2
array5 = np.arange(0, 11, passo)
print(array5)

[ 0  2  4  6  8 10]


In [30]:
#np.linspace() - método que retorna elementos que possuem uma mesma distância entre si,
#retornando n elementos, sendo que n é passado para o método
array6 = np.linspace(0, 100, 5)
print(array6)

[  0.  25.  50.  75. 100.]


In [33]:
#Método para inicializar arrays com 0 - .zeros()
array_zeros = np.zeros(10)
print(array_zeros)

print()
#Caso se deseje mais dimensões, se adiciona mais parênteses e
#se especifica a quantidade de dimensões
matriz_zeros = np.zeros((4,4)) #2 aberturas de parênteses: matriz com 4 linhas e 4 colunas
print(matriz_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [34]:
#De maneira análoga, é possível inicializar arrays com o número 1
array_one = np.ones(10)
print(array_one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## *Atributos de arrays*

In [39]:
#Para saber o tipo de dados armazenados em um array - .dtype
array1 = np.array([81, 19, 22, 25])
print(array1)
print(array1.dtype)

[81 19 22 25]
int64


Importante frisar que o array é uma estrutura de dados homogênea e portanto aceita somente um tipo de dado, diferente das listas.

In [43]:
#Método que retorna o número de elementos em cada dimensão do array - .shape
array_2_dimensoes = np.array([[1,2,3],[3,2,1]])
print(array_2_dimensoes)
print(array_2_dimensoes.shape) #retorna (2,3) ou seja, 2 dimensões com 2 linhas e 3 colunas

[[1 2 3]
 [3 2 1]]
(2, 3)


In [44]:
#Para saber o número total de elementos do array - .size
print(array_2_dimensoes.size)

6


In [46]:
#Casting do tipo de dado do array - .astype()
array_bool = np.array([True, False, True])
print(array_bool)
print(array_bool.dtype)

[ True False  True]
bool


In [49]:
array_cast = array_bool.astype(int) #converte os valores booleanos para inteiros 0 ou 1
print(array_cast)
print(array_cast.dtype)

[1 0 1]
int64


## *Operações com arrays*

In [54]:
#Operações Aritméticas - as operações são realizadas elementos por elemento entre os arrays
array1 = np.array([1,2,3,4])
array2 = np.array([4,3,2,1])

print(array1)
print(array2)

#Soma
soma = array1 + array2
print(f'Soma de {array1} com {array2}: {soma}')

#Multiplicação
mult = array1 * array2
print(print(f'Produto de {array1} com {array2}: {mult}')
)

#Divisão
div = array1 / array2
print(f'Razão de {array1} com {array2}: {div}')


[1 2 3 4]
[4 3 2 1]
Soma de [1 2 3 4] com [4 3 2 1]: [5 5 5 5]
Produto de [1 2 3 4] com [4 3 2 1]: [4 6 6 4]
None
Razão de [1 2 3 4] com [4 3 2 1]: [0.25       0.66666667 1.5        4.        ]


In [57]:
#Operação com Escalar - opera todos os elementos do array com o escalar
#É possível utilizar qualquer operação aritmética
array = np.array([58,62,70,94,2002])

escalar_array = array * 6
print(escalar_array)

[  348   372   420   564 12012]


In [62]:
#Broadcasting - operações entre arrays de diferentes dimensões
array1 = np.array([10,20,30])
array2 = np.array([[1,3,5],[2,4,6]])

print(f'Array1: {array1}')
print(f'Array2: {array2}')

soma = array1 + array2
print(soma)

Array1: [10 20 30]
Array2: [[1 3 5]
 [2 4 6]]
[[11 23 35]
 [12 24 36]]


In [ ]:
#No broadcasting, o numpy adequa a estrutura com menos dimensões, espalhando seus valores virtualmente

## *Funções de agregação*
Funções que resumem os dados presentes no array

In [63]:
#Função que soma todos os elementos do array - sum()
array1 = np.array([1,2,3,4,5])
soma1 = array1.sum()
print(f'Soma dos elementos de {array1}: {soma1}')

Soma dos elementos de [1 2 3 4 5]: 15


In [66]:
#Soma por colunas ou linhas de uma matriz - .sum(axis=0 ou 1) -> 0 para colunas e 1 para linhas
matriz = np.array([[5,10,15,20],[25,30,35,40]])
print(matriz)
soma_coluna = matriz.sum(axis=0)
print(f'Soma das colunas: {soma_coluna}')

soma_linhas = matriz.sum(axis=1)
print(f'Soma das linhas: {soma_linhas}')

[[ 5 10 15 20]
 [25 30 35 40]]
Soma das colunas: [30 40 50 60]
Soma das linhas: [ 50 130]


In [64]:
#Função que calcula a média aritmética dos elementos do array - mean()
array2 = np.array([10,20,30,40])
media = array2.mean()
print(f'A média da matriz {array2} é: {media}')

A média da matriz [10 20 30 40] é: 25.0


In [67]:
#Da mesma forma que o sum, é possível pegar a média somente das
#colunas ou das linhas da matriz, utilizando o axis = 0 ou = 1
media_colunas = matriz.mean(axis = 0)
print(f'Média das colunas da matriz {matriz}: {media_colunas}')
media_linhas = matriz.mean(axis = 1)
print(f'Média das linhas da matriz {matriz}: {media_linhas}')


Média das colunas da matriz [[ 5 10 15 20]
 [25 30 35 40]]: [15. 20. 25. 30.]
Média das linhas da matriz [[ 5 10 15 20]
 [25 30 35 40]]: [12.5 32.5]


In [69]:
#Função que calcula o desvio padrão dos elementos - std.()
array3 = np.array([15,30,45,60])
desvio = array3.std()
print(desvio)

16.77050983124842


In [72]:
#Funções para encontrar o valor mínimo e máximo do array - min() e max()
min = array3.min()
print(min)
max = array3.max()
print(max)

15
60


In [73]:
#Função que retorna o ÍNDICE do maior elemento presente no array
array4 = np.array([[10,20,30,40],[50,80,60,70]])
ind_maior = array4.argmax()
print(ind_maior)

5


## *Operações Lógicas*

In [ ]:
#O resultado das comparações é um array de booleanos que resultam da comparação
#entre os elementos de um array

In [75]:
#Operação que verifica a igualdade entre os elementos de dois arrays
array1 = np.array([1,2,3])
array2 = np.array([1,3,5])

print(array1)
print(array2)

print(array1 == array2)

[1 2 3]
[1 3 5]
[ True False False]


In [77]:
#Saber se um array é maior que outro
maior_que = array1 > array2
print(maior_que)

[False False False]


In [80]:
#Operadores lógicos
#Operador AND - &
array1 = np.array([True, True, False])
array2 = np.array([False, True, False])

array_and = array1 & array2
print(array_and)

[False  True False]


In [82]:
#Utilizando o método .logical_and
np.logical_and(array1, array2)

array([False,  True, False])

In [84]:
#Filtrar o array com uma condição lógica
array = np.array([10,20,30,40,50])

filtro = array > 30

print(filtro)

#Mostrando os elementos
elementos_filtro = array[filtro]

print(elementos_filtro)

[False False False  True  True]
[40 50]


## *Indexação e fatiamento*
Acesso aos elementos e manipulação dos mesmos usando numpy.

In [87]:
#Acesso aos elementos do array
#Array unidimensional
array1 = np.arange(11)
print(array1)


print(array1[0]) #da mesma forma que em listas

[ 0  1  2  3  4  5  6  7  8  9 10]
0


In [89]:
#Acesso em matrizes
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array2)

print(array2[0][1]) #novamente, da mesma forma, especificando a linha e coluna

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [ ]:
#Fatiamento de arrays

In [94]:
#Sintaxe - [índice inicial: índice final: passo]
array = np.arange(10, 101, 10)
print(array)

array_fatiado = array[0:9:2]

print(array_fatiado)

[ 10  20  30  40  50  60  70  80  90 100]
[10 30 50 70 90]


In [95]:
#Fatiar do início até um índice desejado - [:quantidade de elementos desejada]
primeiros_cinco = array[:5]
print(primeiros_cinco)

[10 20 30 40 50]


In [97]:
#Fatiar de um índice até o final - [índice:]
partir_do_quinto = array[5:]
print(partir_do_quinto)

[ 60  70  80  90 100]


## *Indexação Booleana*

In [98]:
#Combinando condições
dados = np.arange(1,11)
print(dados)
condicao1 = dados % 2 == 0
condicao2 = dados < 5

dados_filtrados = dados[condicao1 & condicao2] #somente elementos pares e menores que 5
print(dados_filtrados)

[ 1  2  3  4  5  6  7  8  9 10]
[2 4]


## *Visão x Cópia*
O fatiamento de um array gera a chamada view (visão) do mesmo, o que significa que cada alteração no array fatiado também será executada no array original.
Para que não ocorra alterações indesejadas no original, é possível criar cópias do mesmo.

In [4]:
#Exemplificando a visão de um array
array = np.array([1,2,3,4,5])
print(array)

visao = array[2:4] #fatiando o array
print(visao)

visao[0] = 100 #alterando o primeiro elemento do array fatiado
print(visao)
print(array) #o array original também sofre a alteração

[1 2 3 4 5]
[3 4]
[100   4]
[  1   2 100   4   5]


In [6]:
#Criando uma cópia com o método .copy()
array_copia = array.copy()
print(array_copia)

array_copia[0] = 90 #ao modificar o array copiado, isso não afeta o original
print(array_copia)
print(array)

[  1   2 100   4   5]
[ 90   2 100   4   5]
[  1   2 100   4   5]


## *Manipulação de Shapes*
Processo de alteração das dimensões de um array sem que haja perda de dados.

### Função .reshape()

Permite a alteração da forma de um array, desde que o novo array possua a mesma quantidade de elementos que o original.

In [9]:
array = np.arange(1, 11) #array unidimensional com 10 elementos
print(array)

#Transformando em uma matriz
#É necessário que a matriz possua a mesma quantidade de elementos
#Nesse caso vou usar uma matriz de 2 linhas e 5 colunas
matriz = array.reshape(2, 5)
print(matriz)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
#O parâmetro -1 pode ser utilizado para o cálculo automático
#do eixo restante, desde que seja possível remanejar a estrutura
#com o parâmetro enviado
matriz2 = array.reshape(5, -1)
print(matriz2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [12]:
#Código que gera erro, pois não é possível fazer uma matriz
#de 10 elementos com 3 linhas
matriz2 = array.reshape(3, -1)
print(matriz2)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

In [ ]:
#Em suma, o produto dos n parâmetros deve ser igual a quantidade
#de elementos presentes na estrutura original

### Função newaxis

Adiciona uma nova dimensão ao array.

In [18]:
array = np.arange(1, 6)
print(f'Array original: {array}')
print(f'Shape do array original: {array.shape}')

#Adicionando uma coluna ao array
array_coluna = array[:,np.newaxis] #nessa linha, primeiro eu pego todos os elementos do array, e posteriormente crio a nova coluna
print(f'Array coluna: {array_coluna}')
print(f'Shape do array coluna: {array_coluna.shape}')

#Adicionando uma linha ao array
array_linhas = array[np.newaxis,:] #resulta em um array com 1 linha e 5 colunas
print(f'Array com 2 dimensões: {array_linhas}')
print(f'Shape do array: {array_linhas.shape}')


Array original: [1 2 3 4 5]
Shape do array original: (5,)
Array coluna: [[1]
 [2]
 [3]
 [4]
 [5]]
Shape do array coluna: (5, 1)
Array com 2 dimensões: [[1 2 3 4 5]]
Shape do array: (1, 5)


### Função .expand_dims()

Função que adiciona uma nova dimensão em um eixo específico.

In [20]:
#Sintaxe - np.expand_dims(array, axis = eixo)
#A nova dimensão é especificada por meio do parâmetro axis = eixo
array = np.arange(1, 6)
print(array)

array_expandido = np.expand_dims(array, axis = 1) #adicionando uma coluna ao array
print(array_expandido)
print(array_expandido.shape)

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


### Função .squeeze()


Remove dimensões do array.

In [21]:
print(array_expandido)
arrayx = np.squeeze(array_expandido)
print(arrayx)
print(arrayx.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5]
(5,)


### Transposição de arrays - Função .T

Inverte as dimensões do array, por exemplo:
Uma matriz M[i,j], vira uma matriz M[j,i]

In [22]:
matriz = np.array([[1,2,3,4], [5,6,7,8]])
print(matriz)
print(matriz.shape)
print()

transposta = matriz.T
print(transposta)
print(transposta.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
(4, 2)


### Achatamento de arrays - Funções .flatten() e .ravel()

Transformam um array de n dimensões em um array unidimensional.

**.flatten():** retorna uma cópia do array original (gasta mais memória)

**.ravel():** retorna uma visão do array original

In [23]:
matriz = np.arange(1,10).reshape(3, 3)
print(matriz)
print(matriz.shape)
print()

#achatando a matriz
achatada = matriz.ravel()
print(achatada)
print(achatada.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

[1 2 3 4 5 6 7 8 9]
(9,)


### *Combinação e Divisão de arrays*

### Funções .vstack() e .hstack() - Empilhamentos verticais e horizontais

**.vstack()**: caso sejam mútliplos arrays, eles devem possuir o mesmo número de colunas

**.hstack()**: devem possuir o mesmo número de linhas

In [27]:
#Utilizando .vstack
array1 = np.arange(1,6)
array_v = np.vstack(array1)
print(array_v)

array2 = np.arange(6,11)
array_v2 = np.vstack((array1,array2))
print(array_v2)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [29]:
#Utilizando o .hstack()
matriz = np.arange(1,10).reshape(3,3)
print(matriz)
print()
matriz_h = np.hstack(matriz)
print(matriz_h)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]
